from __future__ import annotations

import re
from pathlib import Path

path = Path(__file__).with_name("pr_c_bootstrap.py")
text = path.read_text(encoding="utf-8")

signature_pattern = re.compile(
    r'''    replace_once\(\n        path,\n        "        invocation_started_monotonic: float \| None = None,\\n"\n        "    \) -> AnalystExperimentResult:\\n"\n        "        invocation_started_at = datetime\.now\(UTC\)\\n",\n        "        invocation_started_monotonic: float \| None = None,\\n"\n        "        query_workers: int = DEFAULT_QUERY_WORKERS,\\n"\n        "    \) -> AnalystExperimentResult:\\n"\n        "        query_workers = validate_query_workers\(query_workers\)\\n"\n        "        invocation_started_at = datetime\.now\(UTC\)\\n",\n    \)\n'''
)
signature_replacement = '''    replace_once(\n        path,\n        "    def run(\\n"\n        "        self,\\n"\n        "        manifest: AnalystExperimentManifest,\\n"\n        "        *,\\n"\n        "        manifest_bytes: bytes,\\n"\n        "        manifest_validation_elapsed_seconds: float = 0.0,\\n"\n        "        invocation_started_monotonic: float | None = None,\\n"\n        "    ) -> AnalystExperimentResult:\\n"\n        "        invocation_started_at = datetime.now(UTC)\\n",\n        "    def run(\\n"\n        "        self,\\n"\n        "        manifest: AnalystExperimentManifest,\\n"\n        "        *,\\n"\n        "        manifest_bytes: bytes,\\n"\n        "        manifest_validation_elapsed_seconds: float = 0.0,\\n"\n        "        invocation_started_monotonic: float | None = None,\\n"\n        "        query_workers: int = DEFAULT_QUERY_WORKERS,\\n"\n        "    ) -> AnalystExperimentResult:\\n"\n        "        query_workers = validate_query_workers(query_workers)\\n"\n        "        invocation_started_at = datetime.now(UTC)\\n",\n    )\n'''
text, count = signature_pattern.subn(lambda _: signature_replacement, text, count=1)
if count != 1:
    raise RuntimeError("expected one ambiguous run-signature patch in bootstrap")

bad_call = '''    # run -> _run_in_workdir\n    replace_once(\n        path,\n        "                            events=events,\\n"\n        "                            timings=timings,\\n"\n        "                        )\\n",\n        "                            events=events,\\n"\n        "                            timings=timings,\\n"\n        "                            query_workers=query_workers,\\n"\n        "                        )\\n",\n    )\n'''
good_call = '''    # run -> _run_in_workdir; anchor on artifact_path so resume cannot match.\n    replace_once(\n        path,\n        "                            artifact_path=artifact_path,\\n"\n        "                            events=events,\\n"\n        "                            timings=timings,\\n"\n        "                        )\\n",\n        "                            artifact_path=artifact_path,\\n"\n        "                            events=events,\\n"\n        "                            timings=timings,\\n"\n        "                            query_workers=query_workers,\\n"\n        "                        )\\n",\n    )\n'''
if text.count(bad_call) != 1:
    raise RuntimeError("expected one ambiguous run-workdir call patch in bootstrap")
text = text.replace(bad_call, good_call, 1)

bad_events = '''    # There are three query_retry/query_failed event blocks with identical family/query prefix.\n    target = ROOT / path\n    text = target.read_text(encoding="utf-8")\n    needle = (\n        "                        stage=\\"search_collection\\",\\n"\n        "                        family_id=family_id,\\n"\n        "                        query=query,\\n"\n    )\n    replacement = (\n        "                        stage=\\"search_collection\\",\\n"\n        "                        worker=worker,\\n"\n        "                        family_id=family_id,\\n"\n        "                        query=query,\\n"\n    )\n    count = text.count(needle)\n    if count != 3:\n        raise RuntimeError(f"expected three query retry/failure event blocks, found {count}")\n    target.write_text(text.replace(needle, replacement), encoding="utf-8")\n'''
good_events = '''    # Query failure/retry blocks live at two indentation depths. Patch both explicitly.\n    target = ROOT / path\n    text = target.read_text(encoding="utf-8")\n    deep_needle = (\n        "                        stage=\\"search_collection\\",\\n"\n        "                        family_id=family_id,\\n"\n        "                        query=query,\\n"\n    )\n    deep_replacement = (\n        "                        stage=\\"search_collection\\",\\n"\n        "                        worker=worker,\\n"\n        "                        family_id=family_id,\\n"\n        "                        query=query,\\n"\n    )\n    shallow_needle = (\n        "                    stage=\\"search_collection\\",\\n"\n        "                    family_id=family_id,\\n"\n        "                    query=query,\\n"\n    )\n    shallow_replacement = (\n        "                    stage=\\"search_collection\\",\\n"\n        "                    worker=worker,\\n"\n        "                    family_id=family_id,\\n"\n        "                    query=query,\\n"\n    )\n    if text.count(deep_needle) != 1:\n        raise RuntimeError("expected one terminal-attempt query_failed event block")\n    if text.count(shallow_needle) != 2:\n        raise RuntimeError("expected retry plus non-transport query failure event blocks")\n    text = text.replace(deep_needle, deep_replacement, 1)\n    text = text.replace(shallow_needle, shallow_replacement)\n    target.write_text(text, encoding="utf-8")\n'''
if text.count(bad_events) != 1:
    raise RuntimeError("expected one ambiguous worker-event patch in bootstrap")
text = text.replace(bad_events, good_events, 1)

path.write_text(text, encoding="utf-8")
